# tests/testthat/test_mr_business_logic.R
#
# Golden-snapshot regression test for mr_business_logic().
#
# Strategy: synthesise a fixed set of inputs (helper-mr_business_logic.R),
# run them through mr_business_logic() with a fixed RNG seed, and compare
# the output to a committed fixture (fixtures/mr_business_logic_golden.rds)
# generated by data-raw/regenerate_mr_business_logic_golden.R.
#
# If this test fails after an INTENTIONAL change to mr_business_logic() or
# a TwoSampleMR upgrade, regenerate the fixture by sourcing the script in
# data-raw/ and commit the new .rds.

skip_if_not_installed("TwoSampleMR")

fixture_path <- testthat::test_path("fixtures", "mr_business_logic_golden.rds")

test_that("golden fixture exists (run tests/testthat/fixtures/regenerate_mr_business_logic_golden.R if missing)", {
  expect_true(
    file.exists(fixture_path),
    info = paste0("Missing fixture: ", fixture_path,
                  ". Regenerate via source('tests/testthat/fixtures/regenerate_mr_business_logic_golden.R').")
  )
})

if (!file.exists(fixture_path)) return(invisible())

golden <- readRDS(fixture_path)
out    <- run_synthetic_mr_business_logic()

test_that("mr_business_logic returns the expected top-level structure", {
  expect_named(out, c("MR_df", "results_df"))
  expect_s3_class(out$MR_df,      "tbl_df")
  expect_s3_class(out$results_df, "tbl_df")
})

test_that("results_df row/column shape matches the golden fixture", {
  expect_equal(nrow(out$results_df), nrow(golden$results_df))
  expect_equal(ncol(out$results_df), ncol(golden$results_df))
  expect_named(out$results_df, names(golden$results_df))
})

test_that("results_df values match the golden fixture", {
  # tolerance = 1e-6 absorbs FP/platform noise but flags real numeric drift.
  expect_equal(out$results_df, golden$results_df, tolerance = 1e-6)
})

test_that("MR_df list-column row counts match the golden fixture", {
  list_cols <- c("harmonised", "mr_summary", "heterogeneity",
                 "egger_intercept", "leaveoneout", "steiger")
  for (col in list_cols) {
    expect_equal(
      vapply(out$MR_df[[col]],    NROW, integer(1)),
      vapply(golden$MR_df[[col]], NROW, integer(1)),
      info = paste0("list-col '", col, "' row counts differ")
    )
  }
})

test_that("MR_df preserves input description column and adds expected results_* columns", {
  expect_equal(out$MR_df$description, golden$MR_df$description)
  expect_true(all(grepl("^results_", grep("^results_", names(out$MR_df), value = TRUE))))
  expect_setequal(
    grep("^results_", names(out$MR_df), value = TRUE),
    grep("^results_", names(golden$MR_df), value = TRUE)
  )
})

test_that("mr_business_logic writes no plot files when plot_output_dir = ''", {
  # run_synthetic_mr_business_logic() passes plot_output_dir = "" so no PNG/PDF
  # should appear under the working directory or tempdir() between calls.
  before <- list.files(tempdir(), pattern = "\\.(png|pdf)$",
                       recursive = TRUE, full.names = TRUE)
  invisible(run_synthetic_mr_business_logic())
  after  <- list.files(tempdir(), pattern = "\\.(png|pdf)$",
                       recursive = TRUE, full.names = TRUE)
  expect_equal(setdiff(after, before), character(0))
})
